### ISSUE TITLE
Final content review

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-grpc-intro#16]
- [x] double check that the gRPC only support EE8 (using `javax.*` packages, and not `jakarta.*`)
- [x] change the System.out code to use JUL
    - see the changes in https://github.com/OpenLiberty/draft-guide-jakarta-websocket/pull/13/files except from the README.adoc and index.html 
- [x] rename the methods in `SystemService.java` file
    - `getPropertiesServer()` to `getServerStreamingProperties()`
    - `getPropertiesClient()` to `getClientStreamingProperties()`
    - `getPropertiesBidirect()` to `getBidirectProperties()`
    - update the README accordingly

**Comment by shin19991207** [comment]
Addressed in https://github.com/OpenLiberty/draft-guide-grpc-intro/pull/17

**Comment by gkwan-ibm** [comment]
`mvn -pl systemproto install` generates class `target/generated-sources/protobuf/grpc-java/io/openliberty/guides/systemproto/SystemServiceGrpc.java` that contains `javax.annotation.Generated`. It is EE8 namespace.

Same issue in https://github.com/grpc/grpc-java/issues/9153, and it may be related to https://github.com/grpc/grpc-java/issues/9179

**Comment by hutchig** [comment]
The solution for javax.annotation.Generated is to post process the generated code with https://openliberty.io/blog/2021/03/17/eclipse-transformer.html as the OpenLiberty FAT bucket does for EE9+ and it will be good for the guide to mention this @gkwan-ibm  ....Actually having reviewed how the FAT tests do this - it would not be easy for users to cut'n'paste the way we do it there, so just a reference to https://openliberty.io/blog/2021/03/17/eclipse-transformer.html is probably best
