### ISSUE TITLE
Update diagram to reflect latest method names

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-grpc-intro#22]
The current diagram included doesn't match that latest method names in code?

Also, consider "getBidiProperties" instead of "getBiDirectProperties".

@shin19991207 @gkwan-ibm

**Comment by gkwan-ibm** [comment]
hi @shin19991207
would you update the code and readme to `getBidirectionalProperties`?

**Comment by gkwan-ibm** [comment]
close
- both issues were fixed
